### ISSUE TITLE
Gauge metric decreases with negative values

### ISSUE THREAD

**Issue by tomasrojas26** [prometheus/statsd_exporter#523] opened 2023-11-05 18:43 UTC
Hi everyone, I'm sending negative values to a gauge metric and it decreases acting as a counter metric but backwards. Do you have the same problem?

Here are the basic tests I'm running:

From linux command line:
```
# Execution 1
echo "deploys.test.gauge.myservice:-1|g" | nc -w 1 -u localhost 8125

# Execution 2
echo "deploys.test.gauge.myservice:-1|g" | nc -w 1 -u localhost 8125

# Execution 3
echo "deploys.test.gauge.myservice:-1|g" | nc -w 1 -u localhost 8125
```

StatsD exporter URL (http://localhost:9102/metrics):
```
### Execution 1
# TYPE deploys_test_gauge_myservice gauge
deploys_test_gauge_myservice -1

### Execution 2
# TYPE deploys_test_gauge_myservice gauge
deploys_test_gauge_myservice -2

### Execution 3
# TYPE deploys_test_gauge_myservice gauge
deploys_test_gauge_myservice -3
```

Thanks in advance!

**Comment by pedro-stanaka** [comment] 2023-12-22 13:39
Ha, I was about to open an issue to talk about that. This is actually a "feature" from the code. But I dunno the history about that and wanted to know why we "aggregate" gauge samples like that. 

Seems to be introduced originally by commit 7fc8727306ab343e76bb1a91ea2d3cd9a0f3aa65, but if we remove these lines (from the latest `master`): 

https://github.com/prometheus/statsd_exporter/blob/9c6e2455218b2c7f55944e5d4da65a9757aa8c24/pkg/line/line.go#L248-L252

it will stop aggregating it like that.

I believe though it is related to something I saw written here: https://issues.apache.org/jira/browse/FLINK-12325.

From statsd docs:
> Adding a sign to the gauge value will change the value, rather than setting it.


My question is now, do we want to keep this behavior or can we change it? Also this would be a breaking change in the exporter.

**Comment by matthiasr** [comment] 2024-01-15 20:42
Making a breaking change in the exporter is not a big deal, but breaking compatibility with the documented statsd protocol is a no go. There's barely documented variation and behavior that we've reimplemented based on observation, but for something that is so clearly called out in the original docs, I don't want to deviate.

The [statsd document](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#gauges) calls out that to get a fixed negative value, you need to send a zero followed by the negative value. If _that_ doesn't work (we really ought to have a test), that's a bug 😅

**Comment by matthiasr** [comment] 2024-01-15 20:43
Generally, the scope of this exporter is to implement the statsd protocol, not to second guess it 😄

**Comment by matthiasr** [comment] 2024-01-15 21:52
#533 to add more tests, reaffirming the existing behavior. This also has implications for possible parallelization work, since we do need to preserve the ordering between the zero and subsequent negative value.

I'm going to close this issue, since it is expected behavior and part of the protocol spec.

**Closed by matthiasr** 2024-01-15 21:52 UTC
