### ISSUE TITLE
dynamic tags cannot be added when metric submit

### ISSUE THREAD

**Issue by apack1001** [prometheus/statsd_exporter#170] opened 2018-12-10 08:46 UTC
Hi, 

Our application introduce different labels (tag) at differenct situation.  It looks likes:

ademon:1223|g|#k1:k1
ademon:1223|g|#k1:k1,k2:v2

This will lead to a failure like that:

A change of configuration created inconsistent metrics for \"ademon\". You have to restart the statsd_exporter, and you should consider the effects on your monitoring setup. Error: a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"ademon\", help: \"Metric autogenerated by statsd_exporter.\", constLabels: {k1=\"k1\",k2=\"v2\"}, variableLabels: []} has different label names or a different help string","source":"exporter.go:339

Will this feature be supported in the feature, tags can be dynamic added to metric?

If not, may I implement this and contribute this feature to this project

**Comment by matthiasr** [comment] 2018-12-11 08:43
In principle this is something I want to support, but it is not easy to implement. The Prometheus client really prefers consistent metrics; I believe we need to convert to the Collector form and ConstMetrics, and make sure to mark the collector as Unchecked. Alternatively/additionally, we could fully handle expanding label sets ourselves but that may some many edge cases that need handling.

In any case, I would wait until #164 is in, it gets us one step closer to this by handling metrics on a name-by-name basis.

This issue is a duplicate of #114, I'll close it in favor of that.

**Closed by matthiasr** 2018-12-11 08:43 UTC
