### ISSUE TITLE
Metric buckets are not clearing

### ISSUE THREAD

**Issue by sciffer** [prometheus/statsd_exporter#21] opened 2015-08-24 21:52 UTC
Once statsd_bridge recieves a metric, it seems to hold a bucket for it (until the process dies).
Sometimes a metric is getting sent once in a while and does not require the persistency, is that by design that it will never clean/remove buckets with Nan values or with Nan values for a long period?

**Comment by juliusv** [comment] 2015-08-24 22:37
@ShalomCohen That's unfortunately pretty much by design due to the slight mismatch between StatsD's model of data sending and Prometheus's. E.g. StatsD sends a packet ever time something should be counted. Prometheus only counts it in memory, but exposes the current counter state forever. So the StatsD-bridge cannot differentiate between a very slowly increasing counter and one that has simply gone away. A hypothetical configuration option could offer you to configure timeouts per metric, but that would be pretty labor-intensive and brittle.

**Comment by Lswith** [comment] 2016-10-20 00:14
I would like something like this for gauges. Looking at https://github.com/etsy/statsd/issues/95 it seems they have this kind of option.

**Comment by matthiasr** [comment] 2018-08-04 17:51
Ah this issue is actually duplicated in #129 now. Since there's more discussion over there I'm going to close this one.

**Closed by matthiasr** 2018-08-04 17:51 UTC
