### ISSUE TITLE
Feature: Completely Dynamic Mappings

### ISSUE THREAD

**Issue by lswith** [prometheus/statsd_exporter#62] opened 2017-02-22 23:09 UTC
# Context
Our statsd server collects a large number of time series for many different hosts. Most of these metrics are in the form of:

`stats.<namespace>.<host-id>.<metric_namespace>.<metric_name>`
or 
`stats.<namespace>.<host-id>.<metric_namespace>.<metric_namespace_2>.<metric_namespace...>.<metric_name>`

These metrics when collected should simply be:
`<escaped_metric_name>{host_id=<host_id>,namespace=<namespace>_<metric_namespace>}`
and
`<escaped_metric_name>{host_id=<host_id>,namespace=<namespace>_<metric_namespace>_<metric_namespace2>_<metric_namespace...>}`

This is hard because our current mappings won't allow for dynamic names and also don't allow for full regex on metrics.

# Solution
I suggest we write the mapping config with full golang regex. This allows full control over how the metric's should be mapped.

## Example Config
```
# This creates the most basic mapping. It escapes the metric and then exports it 
(.*)
name=$1

# This creates the more advanced mapping needed above. All the groups would be escaped automatically. 
stats.([^.]+)\.([^.]+)\.(.+)\.([^.]+)$
name=$4
namespace=$1_$3
host=$2
```

Hopefully we can kick off the discussion

**Comment by SuperQ** [comment] 2017-02-25 07:23
I'm not sure what these namespaces are, can you give a more concrete example?

I'm not sure this will generate valid metric/label combinations from a Prometheus perspective.

**Comment by dene14** [comment] 2017-03-17 18:29
I'm not sure if I can provide more details, but the main subject here is to provide support for fully qualified support for regexps.

There are so many applications that has no native support of prometheus metric scraping, but they do provide statsd interface. Creating custom exporter for every particular application isn't always a good option, thus statsd exporter becomes a good bridge between existing infrastructure and promethes.

The problem is that sometimes structure of exposed statsd metrics may differ a lot between applications, thus you have to align them somehow with rewrites. I think philosophy of promethes is that if you can offload some rewriting to the far end - you should, but for now, there is not enough capabilities to fully align metric structure w/o creating million of pretty similar rewrites on statsd, or you have another option - create rewrites on prometheus core service which is still not good, since the rewrites on core shouldn't be very specific to particular metric subsets.

**Comment by lswith** [comment] 2017-03-24 00:15
Exactly. I need more powerful rewrites in the statsd exporter to make it useful. We have 20,000 metrics going to our statsd servers and if I don't write the correct rewrites, it completely pollutes our Prometheus Servers with crappy metrics.

**Comment by drawks** [comment] 2017-07-31 21:16
This seem like a duplicate of issue #20 

I too would really like this feature.

**Comment by drawks** [comment] 2017-08-04 22:49
I think once #89 and #85 are merged the proposed/requested behavior will work.

**Comment by matthiasr** [comment] 2018-01-18 08:16
We now support regular expressions, and mapping names as well. I think this should cover all your needs? If not, please reopen the issue.

**Closed by matthiasr** 2018-01-18 08:16 UTC
