### ISSUE TITLE
[FEATURE REQUEST] Using both Histogram and Summary with DogStatsd

### ISSUE THREAD

**Issue by gaizeror** [prometheus/statsd_exporter#190] opened 2019-03-19 09:55 UTC
When using DogStatsD, the mapping is not relevant, so we can't enjoy both types.
It would be great if we can decide when to report a Histogram timer and when to report Summary timer. Currently we are locked to the default timer configured in the exporter.

Ideal config will be:

```
defaults:
  timer_type: histogram
  buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5 ]
  match_type: glob
  glob_disable_ordering: false
  ttl: 0 # metrics do not expire
mappings:
# This will be a summary timer.
- match: *_summary
  timer_type: summary
  name: <The real metric name, i.e http_request_ms_summary>
  quantiles:
    - quantile: 0.99
      error: 0.001
    - quantile: 0.95
      error: 0.01
    - quantile: 0.9
      error: 0.05
    - quantile: 0.5
      error: 0.005
```
Thanks!

**Comment by matthiasr** [comment] 2019-03-19 10:00
> When using DogStatsD, the mapping is not relevant, so we can't enjoy both types

uh interesting, the dogstatsd tags should be applied on top of the mapping, so this _should_ be possible.

I don't think `match: *_summary` works like that though – we only allow `*` to match a whole dot-separated segment of the metric. If you do need to match like this, use `match_type: regex` and `match: .*_summary`. Does the metric get mapped to a summary if you (manually) submit one without tags?

**Comment by gaizeror** [comment] 2019-03-19 11:55
> > When using DogStatsD, the mapping is not relevant, so we can't enjoy both types
> 
> uh interesting, the dogstatsd tags should be applied on top of the mapping, so this _should_ be possible.
> 
> I don't think `match: *_summary` works like that though – we only allow `*` to match a whole dot-separated segment of the metric. If you do need to match like this, use `match_type: regex` and `match: .*_summary`. Does the metric get mapped to a summary if you (manually) submit one without tags?

The exporter crashes:

> time="2019-03-19T11:53:56Z" level=fatal msg="AcceptTCP failed: accept tcp [::]:9125: use of closed network connection" source="exporter.go:675"
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> main.escapeMetricName(0x0, 0x0, 0x10, 0x907467)
> 	/app/exporter.go:283 +0xcc
> main.(*Exporter).handleEvent(0xc00018df58, 0x98b680, 0xc000424ba0)
> 	/app/exporter.go:336 +0x1d8
> main.(*Exporter).Listen(0xc00018df58, 0xc00005b020)
> 	/app/exporter.go:308 +0x159
> main.main()
> 	/app/main.go:213 +0x11db
> 
> >

**Comment by matthiasr** [comment] 2019-03-19 12:06
uuuh, ehrm, that should never happen. what was the message you submitted?

**Comment by SuperQ** [comment] 2019-03-19 12:22
Summaries and Histograms are not supported simultaneously.

**Comment by gaizeror** [comment] 2019-03-19 13:03
@matthiasr using python DogStatsD client:
statsd_client.timed(metric_name, metric_tags, use_ms=True)

@SuperQ Thats my feature request :)

**Comment by matthiasr** [comment] 2019-03-19 13:04
in the request that crashed the exporter, what was `metric_name` and
`metric_tags`? I want to record that crash as a separate issue.

**Comment by matthiasr** [comment] 2019-03-19 13:07
What is your use case for mixing the two? I think given a good use case this is reasonable but it may not be entirely trivial to implement.

**Comment by gaizeror** [comment] 2019-03-19 13:08
@matthiasr 
<img width="372" alt="Screen Shot 2019-03-19 at 15 07 55" src="https://user-images.githubusercontent.com/18627927/54608208-e6b96d00-4a58-11e9-8e8c-ba2c5b84bad2.png">

**Comment by gaizeror** [comment] 2019-03-19 13:18
> What is your use case for mixing the two? I think given a good use case this is reasonable but it may not be entirely trivial to implement.

Since there is no way to create specific bucketing per use-case (same root cause, mapping now supported).
Even if it was possible, it's manual and requires developers to decide what are the correct buckets to calculate percentile per use-case. 
So it's easier for developers to enjoy the given summary method.
we have functions that take 0-5 s for example and others that may take 30s or even 2m, so buckets for each use-case are different, and it forces us to create huge bucket list [0.05,0.5,...,1,2.5,5,7.5,...,60,...]

In the other hand, sometimes we would like to get histogram, for example to get the distribution and being able to perform aggregations.

**Comment by matthiasr** [comment] 2019-03-20 09:57
Sooo, while trying to reproduce the crash, I found that this actually already works:

```
[I] ~/s/g/p/statsd_exporter (master|✔) $ ./statsd_exporter --statsd.mapping-config=tmp/190.yaml --log.level=debug &
INFO[0000] Starting StatsD -> Prometheus Exporter (version=, branch=, revision=)  source="main.go:158"
INFO[0000] Build context (go=go1.12, user=, date=)       source="main.go:159"
INFO[0000] Accepting StatsD Traffic: UDP :9125, TCP :9125  source="main.go:160"
INFO[0000] Accepting Prometheus Requests on :9102        source="main.go:161"
[I] ~/s/g/p/statsd_exporter (master|✔) $ echo "foo_summary:1|ms|@0.1" | nc localhost 9125
[I] ~/s/g/p/statsd_exporter (master|✔) $ echo "bar:1|ms|@0.1" | nc localhost 9125
[I] ~/s/g/p/statsd_exporter (master|✔) $ curl http://localhost:9102/metrics | grep -E 'foo|bar'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8659    0  8659    0     0  1418k      0 --:--:-- --:--:-- --:--:-- 1691k
# HELP bar Metric autogenerated by statsd_exporter.
# TYPE bar histogram
bar_bucket{le="0.005"} 10
bar_bucket{le="0.01"} 10
bar_bucket{le="0.025"} 10
bar_bucket{le="0.05"} 10
bar_bucket{le="0.1"} 10
bar_bucket{le="0.25"} 10
bar_bucket{le="0.5"} 10
bar_bucket{le="1"} 10
bar_bucket{le="2.5"} 10
bar_bucket{le="5"} 10
bar_bucket{le="10"} 10
bar_bucket{le="+Inf"} 10
bar_sum 0.010000000000000002
bar_count 10
# HELP foo Metric autogenerated by statsd_exporter.
# TYPE foo summary
foo{quantile="0.5"} 0.001
foo{quantile="0.9"} 0.001
foo{quantile="0.95"} 0.001
foo{quantile="0.99"} 0.001
foo_sum 0.010000000000000002
foo_count 10
[I] ~/s/g/p/statsd_exporter (master|✔) $ fg
Send job 1, './statsd_exporter --statsd.mapping-config=tmp/190.yaml --log.level=debug &' to foreground
^C⏎                                                                                                                                                                                  [I] ~/s/g/p/statsd_exporter (master|✔) $
```

The crash is triggered by the empty name that results from the invalid `"${1}"` reference. Tweak your configuration like this:

```
defaults:
#  timer_type: summary
  timer_type: histogram
  buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
  match_type: glob
  glob_disable_ordering: false
  ttl: 1m
mappings:
# This will be a summary timer.
- match: (.*)_summary
  match_type: regex
  timer_type: summary
  name: "${1}"
  quantiles:
    - quantile: 0.99
      error: 0.001
    - quantile: 0.95
      error: 0.01
    - quantile: 0.9
      error: 0.05
    - quantile: 0.5
      error: 0.005
```

and it will work – note the parenthesis in the regex populating the capture group that you are referencing for the name.

**Comment by matthiasr** [comment] 2019-03-20 10:39
And it also works when specifying tags:

```
[I] ~/s/g/p/statsd_exporter (master|✔) $ echo "bar:1|ms|@0.1|#one:two" | nc localhost 9125
[I] ~/s/g/p/statsd_exporter (master|✔) $ echo "foo_summary:1|ms|@0.1|#one:two" | nc localhost 9125
[I] ~/s/g/p/statsd_exporter (master|✔) $ curl http://localhost:9102/metrics | grep -E 'foo|bar'
# HELP bar Metric autogenerated by statsd_exporter.
# TYPE bar histogram
bar_bucket{one="two",le="0.005"} 10
bar_bucket{one="two",le="0.01"} 10
bar_bucket{one="two",le="0.025"} 10
bar_bucket{one="two",le="0.05"} 10
bar_bucket{one="two",le="0.1"} 10
bar_bucket{one="two",le="0.25"} 10
bar_bucket{one="two",le="0.5"} 10
bar_bucket{one="two",le="1"} 10
bar_bucket{one="two",le="2.5"} 10
bar_bucket{one="two",le="5"} 10
bar_bucket{one="two",le="10"} 10
bar_bucket{one="two",le="+Inf"} 10
bar_sum{one="two"} 0.010000000000000002
bar_count{one="two"} 10
# HELP foo Metric autogenerated by statsd_exporter.
# TYPE foo summary
foo{one="two",quantile="0.5"} 0.001
foo{one="two",quantile="0.9"} 0.001
foo{one="two",quantile="0.95"} 0.001
foo{one="two",quantile="0.99"} 0.001
foo_sum{one="two"} 0.010000000000000002
foo_count{one="two"} 10
```

I'm going to close this issue, since the feature already exists, and open a separate issue for the crash on empty names.

**Closed by matthiasr** 2019-03-20 10:39 UTC
Labels: enhancement, help wanted

**Comment by gaizeror** [comment] 2019-03-20 11:43
Thanks so much for the fast responses, you are the best!
