### ISSUE TITLE
missing debug parameter

### ISSUE THREAD

**Issue by Grummfy** [prometheus/statsd_exporter#132] opened 2018-05-17 07:51 UTC
Hello,
I think the --log.level should be added to the tool, so it's hard to debug stuff in case of issue ;)

thanks

**Comment by matthiasr** [comment] 2018-08-04 17:45
You're right, this should be exposed. If anyone wants to tackle this, please do 😃

**Comment by matthiasr** [comment] 2018-08-10 07:02
Actually, this is a duplicate of #111 – it's not completely straightforward because the log package uses a different package than the exporter. I'll close this issue since there is more information over there.

**Closed by matthiasr** 2018-08-10 07:02 UTC
Labels: bug, good first issue
